### ISSUE TITLE
[Task] SR 진행

### ISSUE THREAD

**Issue by namooni** [codestates/OnWedding#12]
### ISSUE
- Group: `SR`
- Type: `requirement`
- Detail: sr progress

### TODO
1. [x]  프로젝트 기획 및 범위 설정
2. [x]  Front-end 세부 기획 진행
3. [x]  Back-end 세부 기획 진행
4. [x]  Wiki 및 기능 To Do List 작성
5. [x]  Task Card 작성 및 분배
6. [x]  Not To do List 점검

### Labels
- Estimated time: `E: 8h`
- Group : `SR`
- Sprint: `Sprint 1`
- Urgency: `High`
