### ISSUE TITLE
[Task] [client] main 페이지 구현 - 1

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#24]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 전체적인 main페이지 제작

### TODO
1. [x]  main 페이지 기본적인 페이지 틀 구현
2. [x]  최신순으로 기본정렬 후 인기순, 댓글순 으로 정렬 구현 및 버튼 구현
3. [x]  글쓰기 페이지로 이동가능한 버튼 구현
4. [x] 배경 이미지와 배경 글씨 삽입

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2 - Feature`
- Urgency: `1`
