### ISSUE TITLE
[Task] [client] main 페이지 구현 - 2

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#26]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 각 컴포넌트와 연결 및 axios 통신요청으로 받아온 정보를 이용해 목록 구현

### TODO
1. [x]  비로그인시 글쓰기 버튼 비활성화
2. [x]  axios 통신 구현
3. [x]  받아온 DB 정보로 글목록 구현
4. [x] 대략적인 CSS 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2 - Feature`
- Urgency: `1`
