### ISSUE TITLE
[Task] [client] article 페이지 구현 - 2

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#32]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: axios 통신으로 받아온 정보 구현 및 수정 추가 구현

### TODO
1. [x]  axios 통신 구현
2. [x]  받아온 정보로 게시글 구현
3. [x]  수정 추가 구현 및 버튼 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint - 2 Feature`
- Urgency: `2`
