### ISSUE TITLE
[Task] [client] article 페이지 구현 - 3

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#38]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 각종 추가 구현 및 버튼 구현

### TODO
1. [x]  댓글 추가 구현 및 버튼 구현
2. [x] 수정 추가 구현 및 버튼 구현
3. [x] 수정 버튼 클릭시 글쓰기 페이지로 이동
4. [x] 글쓰기 페이지 이동시 게시물 제목 내용 그대로 가져가야함
5. [x] 삭제 구현 및 버튼 구성

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint - 2 Feature`
- Urgency: `2`
