### ISSUE TITLE
[Task] [Client] 로그아웃 페이지 구현

### ISSUE THREAD

**Issue by BassistHeo** [codestates/OnWedding#53]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그아웃 페이지 구현, 로그아웃 버튼 만들기

### TODO

1. [ ] 로그아웃 페이지 작성 
2. [ ] 로그아웃 버튼 구현
3. [ ] 로그아웃 버튼 클릭시 메인 페이지로 리다이렉트 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint - 2 Feature`
- Urgency:  3
