### ISSUE TITLE
[Task] [client] mypage 페이지 구현 - 2

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#60]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: axios 통신으로 받아온 정보로 구현 및 대략적인 CSS 구현

### TODO
1. [x]  axios 통신 구현
2. [x]  받아온 DB 정보로 각 항목 구현
3. [ ]  대략적인 CSS 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint - 2 Feature`
- Urgency: `4`
