### ISSUE TITLE
[Task] [client] comment 컴포넌트 구현

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/OnWedding#68]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: comment 컴포넌트 구현

### TODO
1. [ ]  axios 통신으로 받아온 정보를 이용
2. [ ]  프로필 사진, 닉네임, comment 내용 사용
3. [ ]  댓글쓰기 버튼 클릭시 axios 요청 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint - 2 Feature`
- Urgency: `5`
